import React, { useRef, useLayoutEffect, useState } from 'react';
import { stack, stackOffsetNone, stackOrderAscending, curveMonotoneX, area } from 'd3-shape';
import { scaleLinear } from 'd3-scale';
import { uniq } from 'lodash';
import { max, extent } from 'd3-array';
import { formatNumber, useCardSize } from './../../../helpers/helperFunc';

const EnIndustry = ({
  currentData,
  currentIndicator,
  currentSection,
  locationLabel,
  isThumbnail,
  footnote,
  cardNumber,
}) => {
  // getting sizes of container for maps
  const targetRef = useRef();
  const dimensions = useCardSize(targetRef, cardNumber);

  const [highlighedStream, setHighlightedStream] = useState('');
  const [activeLabel, setactiveLabel] = useState('');

  //   const [currentId, setCurrentId] = useState('');

  // inital variables
  const marginWidth = 0;
  const marginHeight = 0;
  // const paddingHeight = 15;
  let xAxisElements = [];
  let yAxisElements = [];
  let streamEle = [];
  let scaleCategory = function () {
    return undefined;
  };
  let lastYear = '?';
  let percRenewables = 0;
  let secretFootnote = 'In ' + locationLabel[0] + ' ist dieser Vebrauch geheim. ';
  let showBundeslandForLK = false;

  let switchHighlightedStream = function (id) {
    if (currentData !== undefined && currentData.data !== undefined) {
      setHighlightedStream(id);
    }
  };

  let switchActiveLabel = function (index) {
    if (currentData !== undefined && currentData.data !== undefined) {
      setactiveLabel(index);
    }
  };

  if (currentData !== undefined) {
    // parameters for description text
    const lastDataPoint = currentData.data.slice(-1);
    const firstYear = currentData.data[0]['year'];
    lastYear = lastDataPoint[0]['year'];
    const lastRenValue = currentData.data.filter((d) => {
      return d.column === 'Anteil_Erneuerbar' && d.year === '2020';
    });

    // filteredData is generated by checking if all carriers in the
    // data are null on the first year

    let filteredData = currentData.data
    const carriers = uniq(currentData.data.map((d) => { return d.column }));
    const firstYearCarriers = currentData.data.filter((d) => d.year === firstYear && d.value === null);

    if (uniq(firstYearCarriers.map((d) => { return d.column })).length === carriers.length) {
      filteredData = currentData.data.filter((d) => d.year !== firstYear);
    }

    percRenewables = lastRenValue[0].value !== null ? lastRenValue[0].value.toFixed(1) : 0;
    showBundeslandForLK = !currentData.regional && locationLabel[0] !== locationLabel[1];

    // get all energy sources and filter out "insgesamt" and "Anteil_Erneuerbar"
    const uniqueEnergySourceAll = uniq(filteredData.map((d) => d.column));
    const uniqueEnergySourceFiltered = uniqueEnergySourceAll.filter((category) => {
      return (
        category !== 'insgesamt' &&
        category !== 'Anteil_Erneuerbar' &&
        category !== 'Anteil_Geheim' &&
        category !== 'has_regional'
      );
    });

    // setup domains for scaling
    const domainX = extent(filteredData.map((d) => +d.year));
    const xScale = scaleLinear()
      .domain(domainX)
      .range([marginWidth, dimensions.width - marginWidth]);
    const domainY = [0, max(filteredData.map((d) => d.value))];
    const yScale = scaleLinear().domain(domainY).range([dimensions.height, marginHeight]).nice();

    // get unique years from data
    const uniqueYears = uniq(filteredData.map((d) => +d.year));

    // create elements for horizontal axis, plus labels
    xAxisElements = uniqueYears.map((year, a) => {
      return {
        label: year,
        x: xScale(year),
      };
    });

    //create elements for y axis
    const yAxisValues = yScale.ticks(3);
    yAxisElements = yAxisValues.map((d) => {
      return {
        label: `${formatNumber(d)}`,
        x: yScale(d),
      };
    });

    // create area for streams
    const areaGen = area()
      .x((d) => xScale(d.data.year))
      .y0((d) => yScale(d[0]))
      .y1((d) => yScale(d[1]))
      .curve(curveMonotoneX);

    // prepare data for stacking
    const stackData = [];
    uniqueYears.forEach((year, y) => {
      const currentYearData = filteredData.filter((d) => +d.year === year);

      const el = {};
      currentYearData.map((d) => {
        el.year = d.year;
        const nameOfEnergySource = d.column;
        return (el[nameOfEnergySource] = d.value !== null ? d.value : 0);
      });
      stackData.push(el);
    });

    // create stacks
    const stacks = stack()
      .keys(uniqueEnergySourceFiltered)
      .order(stackOrderAscending)
      .offset(stackOffsetNone);
    const stackedSeries = stacks(stackData);

    // stream graph
    streamEle = stackedSeries.map((stream, s) => {
      const maxStreamValue = max(
        stackData.map((d) => {
          return d['year'] !== 1992 && +d['year'] !== 2020 ? d[stream.key] : 0;
        })
      );

      let yearOfMax = 0;
      let indexOfMax = 0;

      stackData.forEach((d, i) => {
        if (d[stream.key] === maxStreamValue) {
          yearOfMax = d.year;
          indexOfMax = i;
        }
      });

      const labelRects = [];
      for (let index = 0; index < stream['length']; index++) {
        const scaledFloor = yScale(stream[index][0]);
        const scaledCeil = yScale(stream[index][1]);
        const year = stackData[index].year;
        const value = stackData[index][stream.key];
        let x = xScale(year);
        if (x + 50 > dimensions.width - marginWidth) x -= 20;

        const y = Math.abs(scaledCeil);
        const yValue = Math.abs(scaledFloor - (scaledFloor - scaledCeil) / 2);

        let xValue = xScale(year);
        if (xValue + 40 > dimensions.width - marginWidth) {
          xValue -= 65;
        } else if (xValue + 50 > dimensions.width - marginWidth) {
          xValue -= 30;
        }

        const height = Math.abs(scaledCeil - scaledFloor);
        const labelEl = {
          x,
          y,
          xValue,
          yValue,
          height,
          value,
        };

        labelRects.push(labelEl);
      }

      return {
        klass: stream.key.substring(0, 3) + '-stream',
        id: stream.key,
        path: areaGen(stream),
        xPos: xScale(yearOfMax),
        labels: labelRects,
        yPos: yScale(stream[indexOfMax][0] - (stream[indexOfMax][0] - stream[indexOfMax][1]) / 2),
        height: yScale(stream[indexOfMax][0] - stream[indexOfMax][1]),
        width: stream.key.length,
        threshold:
          highlighedStream === stream.key || (maxStreamValue > 50000 && highlighedStream === ''), //Fixed value for now, maybe make it dynamic?
        maxStreamValue,
      };
    });
  }

  return (
    <div
      className={`energy-industry horizontal-bottom-layout ${isThumbnail ? 'is-thumbnail' : ''}`}
    >
      <div className="visualization-container" ref={targetRef}>
        <svg className="energy-industry chart" width="100%" height="100%">
          <g className="x-axis">
            {xAxisElements.map((axis, a) => {
              if (a % 2 !== 0) {
                return (
                  <g key={a} transform={`translate(${axis.x + 1}, 0)`}>
                    <line
                      x1="0"
                      x2="0"
                      y1={marginHeight}
                      y2={dimensions.height - marginHeight}
                      stroke="black"
                    />
                    {/* // YEAR */}
                    <text
                      x="-18"
                      y={marginHeight + 15}
                      textAnchor="middle"
                      transform={
                        dimensions.width <= 515 ? `rotate(-90, -10, ${marginHeight + 10})` : ''
                      }
                    >
                      {axis.label}
                    </text>
                  </g>
                );
              } else {
                return null;
              }
            })}
          </g>
          <g className="streams-container">
            {streamEle.map((stream, s) => {
              return (
                <g
                  key={s}
                  className={`stream ${stream.klass}`}
                  onMouseEnter={() => switchHighlightedStream(stream.id)}
                  onMouseLeave={() => switchHighlightedStream('')}
                >
                  <path className={`path ${stream.id}`} d={stream.path} />
                </g>
              );
            })}
          </g>
          <g className="y-axis">
            {yAxisElements.map(function (axis, a) {
              if (a === 0) return;
              return (
                <g
                  transform={`translate(0, ${axis.x})`}
                  key={a}
                  className={`${yAxisElements.length - 1 === a ? 'last-line' : ''}`}
                >
                  <line x1="0" x2={dimensions.width} y1="0" y2="0" />
                  <text x={dimensions.width - marginWidth} y="-5" textAnchor="end">
                    {axis.label}
                  </text>
                </g>
              );
            })}
          </g>
          <g className="streams-labels-container">
            {streamEle.map((label, l) => {
              return (
                <g key={l}>
                  <g className="label">
                    <foreignObject
                      className={label.threshold ? 'visible' : 'invisible'}
                      x={label.xPos - label.width * 2 > 0 ? label.xPos - label.width * 2 : 0}
                      y={label.yPos - 8}
                      width="1"
                      height="1"
                    >
                      <div xmlns="http://www.w3.org/1999/xhtml" className={label.klass}>
                        <p>{label.id}</p>
                      </div>
                    </foreignObject>
                  </g>
                </g>
              );
            })}
          </g>
          <g className="years-labels-container">
            {streamEle.map((stream, s) => {
              return (
                <g
                  key={s}
                  className="stream-labels"
                  onMouseEnter={() => switchHighlightedStream(stream.id)}
                  onMouseLeave={() => switchHighlightedStream('')}
                >
                  {stream.labels.map((label, l) => {
                    return (
                      <g key={l}>
                        <rect
                          x={label.x}
                          y={label.y}
                          width="40"
                          height={label.height}
                          opacity="0"
                          onMouseEnter={() => switchActiveLabel(l)}
                          onMouseLeave={() => switchActiveLabel('')}
                        />
                        {label.value !== 0 && (
                          <g
                            className={`interactive-labels ${activeLabel === l ? 'active-label' : ''
                              }`}
                            transform={`translate(${label.xValue}, ${label.yValue})`}
                          >
                            <foreignObject
                              className={stream.threshold ? 'visible' : 'invisible'}
                              x="0"
                              y="0"
                              width="1"
                              height="1"
                            >
                              <div xmlns="http://www.w3.org/1999/xhtml" className={stream.klass}>
                                <p>{formatNumber(label.value)} TJ</p>
                              </div>
                            </foreignObject>
                          </g>
                        )}
                      </g>
                    );
                  })}
                </g>
              );
            })}
          </g>
        </svg>
      </div>
      <div className="description">
        <div className="title">
          <h4>
            Der Energieverbrauch in der Industrie in{' '}
            <span className="locationLabel">
              {showBundeslandForLK ? locationLabel[1] : locationLabel[0]}
            </span>{' '}
            basiert im Jahr {lastYear} zu{' '}
            <span className="second-value"> {formatNumber(percRenewables)} %</span> auf{' '}
            <span className="second-value"> erneuerbaren Energien</span>.{' '}
            {showBundeslandForLK && secretFootnote}
            {footnote}
            {footnote !== '' && '.'}
          </h4>
        </div>
      </div>
    </div>
  );
};

export default EnIndustry;
